name: Validate

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events
  pull_request_target:
    types: [opened, synchronize, reopened]

  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: 'ğŸ•µï¸â€â™‚ï¸ Lint'
    runs-on: [self-hosted, linux]
    container: node:lts-bullseye

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'âš™ï¸ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@atos-design'

      - name: 'â¡ï¸ Configure NPM Proxy'
        uses: de-als-cycos-dev/actions-npm-proxy@v1

      - name: 'â›“ï¸ Install dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: 'âœ… Lint code'
        run: npm run lint

      - name: 'ğŸ§¹ Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1

  build:
    name: 'ğŸ› ï¸ Build'
    needs: [lint]
    runs-on: [self-hosted, linux]
    container: node:lts-bullseye

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'âš™ï¸ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@atos-design'

      - name: 'â¡ï¸ Configure NPM Proxy'
        uses: de-als-cycos-dev/actions-npm-proxy@v1

      - name: 'â›“ï¸ Install dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: 'ğŸ› ï¸ Build'
        run: npm run build

      - name: 'ğŸ§¹ Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1

  test:
    name: 'ğŸ§ª Test'
    needs: [lint]
    runs-on: [self-hosted, linux]
    container: mcr.microsoft.com/playwright

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'âš™ï¸ Use Node.js'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@atos-design'

      - name: 'â¡ï¸ Configure NPM Proxy'
        uses: de-als-cycos-dev/actions-npm-proxy@v1

      - name: 'â›“ï¸ Install dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: 'ğŸ› ï¸ Build'
        run: npm run build

      - name: 'ğŸ§« Run tests'
        run: npm test

      - name: 'ğŸ§¹ Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1

  codeql:
    name: 'ğŸª² CodeQL'
    needs: [lint]
    runs-on: [self-hosted, linux]
    container: node:lts-bullseye
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Initializes the CodeQL tools for scanning.
      - name: ' ğŸª¡ Initialize CodeQL'
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main
          queries: +security-extended

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: 'ğŸ› ï¸ Autobuild'
        uses: github/codeql-action/autobuild@v1

      - name: 'ğŸ•µï¸ Perform CodeQL Analysis'
        uses: github/codeql-action/analyze@v1

      - name: 'ğŸ§¹ Cleanup workspace'
        uses: ATOS-Actions/clean-self-hosted-runner@v1
